# Site settings
title: llokr's Blog
subtitle: Backend & Cloud Engineering
email: ghdwlsrl100@gachon.ac.kr
description: This blog is about my study records.
baseurl: ""
url: "https://llokr1.github.io"
author:
street_address: 경기도 의정부시
city: 
state: 
zip_code: 
country: Republic of Korea
phone: 010-5850-0061

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/llokr1
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
