# Site settings
title: llokr's Blog
subtitle: Backend & Cloud Engineering
email: ghdwlsrl100@gachon.ac.kr
description: This blog is about my study records.
baseurl: ""
url: "https://llokr1.github.io"
author:
street_address: 경기도 의정부시
city: 
state: 
zip_code: 
country: Republic of Korea
phone: 010-5850-0061

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
